#!/bin/bash

function print_help_msg {
    echo  -e "Usage: get_clib_so_dependencies ENV_NAME OUTPUT_FILE_PATH"
    echo -e "Get shared object library dependencies for netcdf/hdf5 debugging assistance.\n"
    echo -e "ENV_NAME - e.g. - clouddrift, clouddrift-pr"
    echo -e "OUTPUT_FILE_PATH - e.g. - ./debug-output/clib_so_dependencies_output.txt"
    echo -e "\n--help: display this help message\n"
}
arg_count=0
for arg in $@
do
    if [[ "$arg" == "--help" ]]
    then
        print_help_msg
        exit 0
    else
        arg_count=$((arg_count+1))
    fi
done

if [[ $arg_count == 2 ]]
then
    env_location=$(conda env list --json | jq ".envs[]|select(endswith(\"${1}\"))" | awk -F "\"" "{print \$2}")
    echo "Pulling clib shared obj dependencies for environment located in [${env_location}]"
    ldd ${env_location}/lib/python3*/site-packages/{netCDF4,h5py}/*.so > $2
else
    echo "ERROR: Didn't provide the correct number of arguments. Exiting.\n"
    print_help_msg
fi
