name: Lint

# Controls when the workflow will run
on:
  # Triggers on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Install dependencies
        run: uv sync --frozen
      - name: Lint
        run: uv run ruff check
      - name: Format
        run: uv run ruff format --check
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Install dependencies
        run: uv sync --frozen
      - name: Run mypy
        run: uv run mypy
