name: PyPI

on:
  release:
    types:
      - published
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    if: github.repository == 'Cloud-Drift/clouddrift'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Install the project
        run: uv sync --frozen --no-group dev
      - name: Build wheel
        run: uv build
      - name: Check built artifacts version
        run: |
          uvx twine check dist/*
          pwd
          if [ -f dist/clouddrift-0.0.0.tar.gz ]; then
            echo "Invalid version number"
            exit 1
          else
            echo "Looks good"
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: releases
          path: dist

  test-built-dist:
    needs: build-artifacts
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: releases
          path: dist
      - name: List contents of built dist
        run: |
          ls -ltrh
          ls -ltrh dist
      - name: Verify the built dist/wheel is valid
        run: |
          uv pip install dist/clouddrift*.whl
          uv run python -c "import clouddrift; print(clouddrift.__version__)"
      - name: Publish package to TestPyPI
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

  upload-to-pypi:
    needs: test-built-dist
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: releases
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
